### ISSUE TITLE
Window Controls Not Lining Up With the Theme

### ISSUE THREAD

**Issue by Tnings** [zuzumi-f/Moon-Rabbits-Dream-About-Virtual#3]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/55812511/190932096-44766141-828e-44e1-b93f-768e9887b1ff.png">

As shown in the image, the macos window controls aren't in the correct place.

**Comment by zuzumi-f** [comment]
mac os buttons are not customizable since they're part of the system and not the app itself... i can't do anything with css
