### ISSUE TITLE
Moon rabbit discord theme

### ISSUE THREAD

**Issue by firingthoughts** [zuzumi-f/Moon-Rabbits-Dream-About-Virtual#8]
this custom theme isn't working for me? It looks exactly like regular discord, only changes some text colors.  Also the profile pictures for everyone show up like this. I don't know what i'm doing wrong, lol.

i even copied the content of imported urls in "custom CSS" tab.

![Capture](https://github.com/zuzumi-f/Moon-Rabbits-Dream-About-Virtual/assets/73408079/09186b92-8827-448e-ae50-9e79f249adc8)

**Comment by coolesding** [comment]
last update 2 months ago, either use a different one or use a script to update all classes

**Comment by ferivoq** [comment]
Were you able to fix it? Same problem

**Comment by firingthoughts** [comment]
nopee

**Comment by silverhandsan** [comment]
bumpp

**Comment by zuzumi-f** [comment]
theme fixed for now
